### ISSUE TITLE
Move off of Airtable API keys

### ISSUE THREAD

**Issue by jasoncavanaugh** [grassrootsgrocery/admin-portal#93]
As per this article https://support.airtable.com/docs/airtable-api-key-deprecation-notice, Airtable API keys will be deprecated on February 1st, 2024. Since our backend is using these keys to access the Airtable API, we need to move to the suggested alternatives at some point in the future.

**Comment by mattsahn** [comment]
Good call, @jasoncavanaugh.  For new developers, i've been generating personal access tokens, so they all use those already.  For the main prod app, I generated an access token for it from our pseudo-system account and replaced that as the AIRTABLE_API_KEY env variable in the Railway deployment. So, I think we're all good, though we need to update any other cases of API key usage. The other big area we connect to Airtable with is Make.com, but those use proper OAuth integrations already.

@hgreenhut, are there other areas that might be using Airtable API key that need to be updated?

I'll close this issue since admin-portal is remediated.

**Comment by hgreenhut** [comment]
@mattsahn, I moved the Airtable connection in Hubspot to a personal access token with access to our main v2 base and the "Hubspot New Deals" base that a workflow uses to trigger a webhook when new deals are created.

I also switched the Hubspot connection in on2air to OAuth.
